bugfix mount functions

diff --git a/scripts/executable_fun-mount b/scripts/executable_fun-mount
--- a/scripts/executable_fun-mount
+++ b/scripts/executable_fun-mount
@@ -24,6 +24,14 @@ BL=""
 
 # Available options
 opt=":d:f:b:h"
+local OPTIND
+
+if [[ ! $@ =~ ^\-.+ ]]
+then
+  echo "The script requires an argument, aborting"
+  _help
+  exit 1
+fi
 
 
 while getopts "${opt}" arg; do
@@ -51,6 +59,7 @@ while getopts "${opt}" arg; do
       ;;
   esac
 done
+shift $((OPTIND-1))
 
 printf "\nDevice = $DEV"
 printf "\nFile System = $FS\n"
diff --git a/scripts/executable_fun-umount b/scripts/executable_fun-umount
--- a/scripts/executable_fun-umount
+++ b/scripts/executable_fun-umount
@@ -22,6 +22,12 @@ FS=""
 
 # Available options
 opt=":f:b:h"
+if [[ ! $@ =~ ^\-.+ ]]
+then
+  echo "The script requires an argument, aborting"
+  _help
+  exit 1
+fi
 
 while getopts "${opt}" arg; do
   case $arg in
